export const PARTICIPATING_TEAMS: string[] = [
  'Alemania',
  'Arabia Saudita',
  'Argelia',
  'Argentina',
  'Australia',
  'Austria',
  'Bélgica',
  'Brasil',
  'Cabo Verde',
  'Canadá',
  'Catar',
  'Colombia',
  'Corea del Sur',
  'Costa de Marfil',
  'Croacia',
  'Curazao',
  'Ecuador',
  'Egipto',
  'Escocia',
  'España',
  'Estados Unidos',
  'Francia',
  'Ghana',
  'Haití',
  'Inglaterra',
  'Irán',
  'Japón',
  'Jordania',
  'Marruecos',
  'México',
  'Noruega',
  'Nueva Zelanda',
  'Países Bajos',
  'Panamá',
  'Paraguay',
  'Portugal',
  'Senegal',
  'Sudáfrica',
  'Suiza',
  'Túnez',
  'Uruguay',
  'Uzbekistán',
];

export const BONUS_PLAYERS_PLACEHOLDER: string[] = [
  'Lionel Messi',
  'Kylian Mbappé',
  'Vinicius Jr',
  'Jude Bellingham',
  'Erling Haaland',
  'Mohamed Salah',
  'Harry Kane',
  'Kevin De Bruyne',
  'Rodri',
  'Antoine Griezmann',
];
